apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
