apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"